// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vglomjamzoackguysqqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnbG9tamFtem9hY2tndXlzcXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTI1MDIsImV4cCI6MjA2MjY4ODUwMn0.wlIDnrjbJrwQXyP0o7rV05Dn30-HImL_SFj_73pRqVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);